name: ServerControl
version: 0.0.1
author: rcaudillo
main: com.rcaudillo.servercontrol.ServerControl
api-version: 1.16
commands:
  serverinfo:
    description: Gets server info
    usage: /<command>
    aliases: server-info
